cd /home/hcmg/kunhee/Labor/Bayada_data

use pre_hncorrect, clear

*manually change the hospital name in the referral source data

replace newname = "bon secours depaul medical center" if hospname=="bon secours memorial regional medical center" & state=="VA"
replace newname = "bayshore medical center" if hospname=="east houston regional medical center" & state=="TX"
replace newname = "memorial hermann texas medical cntr" if hospname=="memorial herman hopsital" & state=="TX"
replace newname = "baptist health system" if hospname=="st lukes baptist hospital" & state=="TX"

*AZ
replace newname = "phoenix baptist hospital" if (hospname=="arizona heart hospital" | hospname=="arizona heart institute") & state=="AZ"
replace nothosp = 1 if hospname=="cancer treatment centers of america" & state=="AZ"
replace hosp_noprvn = 1 if hospname=="catalina pointe arthritis" & state=="AZ"
replace nothosp = 1 if hospname=="coronado healthcare center" & state=="AZ"
replace type = "SKILLED NURSING FACILITY/REHAB FACILITY" if hospname=="coronado healthcare center" & state=="AZ"
replace type = "SKILLED NURSING FACILITY/REHAB FACILITY" if hospname=="desert blossom" & state=="AZ"

replace newname = "baptist health medical center arkadelphia" if hospname== "baptist health medical center" & state=="AR"
replace newname = "arizona orthopedic surgical hospital" if hospname=="arizona orthopedic surgical hospital chandler" & state=="AZ"
replace newname = "az spine and joint hospital" if hospname=="arizona spine and joint" & state=="AZ"
replace newname = "arrowhead community hospital" if hospname=="arrowhead hospital" & state=="AZ"
replace newname = "banner boswell medical center" if hospname=="banner boswell medical center and rehab" & state=="AZ"
replace newname = "banner desert medical center" if hospname=="banner desert" & state=="AZ"
replace newname = "banner good samaritan medical center" if hospname=="banner university medical center phoenix" & state=="AZ"
replace newname = "university medical center" if hospname=="banner university of arizona umc/uamc" & state=="AZ"
replace newname = "university physicians hospital" if hospname=="banner university of arizona south campus/uamc" & state=="AZ"
replace newname = "st josephs hospital and medical center" if hospname=="barrows neurological institute" & state=="AZ"
replace newname = "canyon vista medical center" if hospname=="canyon vista medical center sierra vista" & state=="AZ"
replace newname = "carondelet heart and vascular instit" if hospname=="carondelet heart and vascular institute chvi tucson" & state=="AZ"
replace newname = "wickenburg community hospital" if hospname=="community hospital clinic congress" & state=="AZ"
replace newname = "copper queen community hospital" if hospname=="copper queen hospital" & state=="AZ"
replace newname = "cornerstone hosp of se arizona" if hospname=="cornerstone hospital tucson" & state=="AZ"
replace newname = "banner boswell medical center" if hospname=="del webb hospital sun city" & state=="AZ"
replace newname = "banner good samaritan medical center" if hospname=="banner good samaritan hospital phoenix" & state=="AZ"
replace newname = "carondelet st marys hospital" if hospname=="carondelet st marys" & state=="AZ"
replace newname = "st lukes medical center" if hospname=="duplicate st lukes hospital phoenix" & state=="AZ"
replace newname = "john c lincoln hospital north mountain" if hospname=="john c lincoln north mountain" & state=="AZ"
replace newname = "maryvale hospital medical center" if hospname=="maryvale hospital" & state=="AZ"
replace newname = "mayo clinic hospital" if (hospname=="mayo clinic arizona" | hospname=="mayo clinic scottsdale" | hospname=="mayo hospital") & state=="AZ"
replace newname = "mercy gilbert medical center" if hospname=="mercy gilbert" & state=="AZ"
replace newname = "northwest medical center" if hospname=="northwest medical center nwmc" & state=="AZ"
replace newname = "northwest medical center oro valley" if hospname=="oro valley hospital" & state=="AZ"
replace newname = "st lukes medical center" if hospname=="phoenix st lukes hospital" & state=="AZ"
replace newname = "scottsdale healthcare osborn" if hospname=="scottsdale healthcare osborn medical center" & state=="AZ"
replace newname = "scottsdale healthcare shea" if hospname=="scottsdale healthcare shea medical center" & state=="AZ"
replace newname = "ssh arizona" if hospname=="select specialty hospital scottsdale" & state=="AZ"
replace newname = "carondelet st joseph hospital" if hospname=="st josephs hospital/carondelet tucson" & state=="AZ"
replace newname = "st josephs hospital and medical center" if hospname=="st josephs medical center peoria north" & state=="AZ"
replace newname = "st lukes behavioral health" if hospname=="st lukes behavioral health center" & state=="AZ"
replace newname = "st lukes medical center" if hospname=="st lukes hospital" & state=="AZ"
replace newname = "st lukes medical center" if hospname=="st lukes medical center phoenix" & state=="AZ"
replace newname = "carondelet st marys hospital" if hospname=="st marys hospital/carondelet tucson" & state=="AZ"
replace newname = "ssh phoenix" if hospname=="surgical hospital of phoenix" & state=="AZ"
replace newname = "st lukes medical center" if hospname=="tempe st lukes" & state=="AZ"
replace newname = "banner thunderbird medical center" if hospname=="thunderbird samaritan hospital" & state=="AZ"
replace newname = "trillium specialty east" if hospname=="trillium specialty hospital" & state=="AZ"
replace newname = "university medical center" if hospname=="university of arizona cancer center" & state=="AZ"
replace newname = "western arizona regional medical cen" if hospname=="western regional medical center" & state=="AZ"
replace newname = "wickenburg community hospital" if hospname=="wickenburg regional health center" & state=="AZ"
replace newname = "northwest medical center" if hospname=="wound care center at northwest nwmc" & state=="AZ"
replace newname = "yavapai regional medical center" if (hospname=="yavapai regional medical center east" | hospname=="yavapai regional medical center west") & state=="AZ"

*CA
replace newname = "hoag memorial hospital presbyterian" if hospname=="hoag memorial hospital" & state=="CA"
replace newname = "scripps memorial hospital encinitas" if hospname=="scripps memorial hospital" & state=="CA"
replace newname = "sonoma valley health care district" if hospname=="sonoma valley hospital" & state=="CA"
replace newname = "mission hospital regional med center" if hospname=="st joseph mission hospital" & state=="CA"

*CO
replace newname = "boulder community hospital" if hospname=="boulder medical center" & state=="CO"
replace newname = "north valley rehab hospital" if hospname=="vibra hospital" & state=="CO"

replace newname = "avista adventist hospital" if hospname=="avista hospital" & state=="CO"
replace newname = "university of co hospital" if hospname=="childrens hospital of colorado" & state=="CO"
replace newname = "colorado acute specialy hosp" if hospname=="colorado acute hospital" & state=="CO"
replace newname = "denver health medical center" if hospname=="denver health" & state=="CO"
replace newname = "exempla saint joseph hospital" if hospname=="exempla st josephs hospital" & state=="CO"
replace newname = "exempla good samaritan medical center" if hospname=="good samaritan hospital layfayette" & state=="CO"
replace newname = "healthsouth rehab of colorado sprin" if hospname=="healthsouth rehabilitation hospital of colorado sp" & state=="CO"
replace newname = "healthsouth rehabilitation hospital" if hospname=="healthsouth rehabilitation hospital of denver" & state=="CO"
replace newname = "kindred hospital aurora" if hospname=="kindred hospital aurora co" & state=="CO"
replace newname = "kindred hospital denver" if hospname=="kindred hospital denver co" & state=="CO"
replace newname = "exempla lutheran medical center" if hospname=="lutheran medical center" & state=="CO"
replace newname = "medical center of aurora" if hospname=="medical center of aurora senior care center" & state=="CO"
replace newname = "exempla saint joseph hospital" if hospname=="medical oncology exempla saint joseph" & state=="CO"
replace newname = "memorial hospital central" if hospname=="memorial hospital north" & state=="CO"
replace newname = "north colorado medical center" if hospname=="northern colorado medical center" & state=="CO"
replace newname = "penrose/st francis healthcare" if (hospname=="penrose hospital" | hospname=="penrose main hospital" | hospname=="saint francis medical center") & state=="CO"
replace newname = "platte valley medical center" if hospname=="platte valley hospital" & state=="CO"
replace newname = "presbyterian st lukes medical center" if hospname=="presbyterian/st lukes medical center denver" & state=="CO"
replace newname = "saint joseph hospital" if hospname=="saint joseph hospital denver" & state=="CO"
replace newname = "ssh colorado springs" if (hospname=="select hospital" | hospname=="select long term care hospital") & state=="CO"
replace newname = "ssh denver" if (regexm(hospname,"select specialty hospital denver south") | hospname=="select specialty p/sl") & state=="CO"
replace newname = "sky ridge medical center" if hospname=="sky ridge medical center duplicate" & state=="CO"
replace newname = "st anthony north" if hospname=="st anthonys hospital north" & state=="CO"
replace newname = "st anthony hospital" if hospname=="st anthonys west" & state=="CO"
replace newname = "saint joseph hospital" if (hospname=="st joseph caritas clinic" | hospname=="st josephs cancer center" )& state=="CO"
replace newname = "st marys hospital and medical center" if hospname=="st marys hospital grand junction" & state=="CO"
replace newname = "st thomas more hospital" if hospname=="st thomas moore hospital" & state=="CO"
replace newname = "swedish medical center" if hospname=="swedish family medicine" & state=="CO"
replace newname = "university of co hospital" if (hospname=="university of colorado hospital" | hospname=="university of colorado hospital duplicate") & state=="CO"

replace newname = "hospital for special care" if hospname=="hospital for speical care" & state=="CT"
replace newname = "lawrence and memorial hospital" if hospname=="lawrence memorial hospital" & state=="CT"
replace newname = "midstate medical center" if hospname=="midstate hospital" & state=="CT"
replace newname = "mount sinai rehabilitation hosptial" if hospname=="mount sinai rehab hospital" & state=="CT"
replace newname = "new milford hospital" if hospname=="new milford" & state=="CT"
replace newname = "norwalk hospital" if hospname=="norwalk hospital wound care center" & state=="CT"
replace newname = "st vincents medical center" if hospname=="saint vincents hospital do not use" & state=="CT"
replace newname = "yale new haven hospital" if hospname=="yale new haven hospital saint raphael campus" & state=="CT"

replace newname = "george washington univ hospital" if hospname=="george washington university hospital" & state=="DC"
replace newname = "georgetown university hospital" if hospname=="georgetown hospital" & state=="DC"
replace newname = "national rehabilitation hospital" if hospname=="medstar national rehabilitation network" & state=="DC"
replace newname = "providence hospital" if hospname=="providence hospital dc" & state=="DC"

replace newname = "kent general hospital" if hospname=="bayhealth medical center kent general" & state=="DE"
replace newname = "milford memorial hospital" if hospname=="bayhealth medical center milford memorial" & state=="DE"
replace newname = "christiana care health system" if (hospname=="christiana care health system ch cchs" | hospname=="christiana gynecologic oncology" | hospname=="christiana hospital") & state=="DE"
replace newname = "dover behavioral health system" if hospname=="dover behavioral health" & state=="DE"
replace newname = "meadow wood hospital" if hospname=="meadowwood behavioral health system" & state=="DE"
replace newname = "milford memorial hospital" if hospname=="milford memorial hospital delaware" & state=="DE"
replace newname = "alfred i dupont hosp for children" if hospname=="nemours/dupont hospital for children" & state=="DE"
replace newname = "rockford" if hospname=="rockford center" & state=="DE"
replace newname = "ssh wilmington" if hospname=="select specialty hosptial de" & state=="DE"
replace newname = "christiana care health system" if hospname=="wilmington hospital" & state=="DE"
replace newname = "st francis hospital wilmington" if (hospname=="st francis hospital" | hospname=="saint francis healthcare") & state=="DE"

replace newname = "h lee moffitt cancer center" if hospname=="moffitt cancer center" & state=="FL"
replace newname = "st josephs hospital" if hospname=="st josephs hospital north" & state=="DE"

replace newname = "brandon regional hospital" if hospname=="brandon regional hospital brh" & state=="FL"
replace newname = "citrus memorial hospital" if hospname=="citrus memorial health syste" & state=="FL"
replace newname = "florida hospital carrollwood" if hospname=="florida hospital of carrolwood" & state=="FL"
replace newname = "florida hospital tampa" if hospname=="florida hospital of fletcher" & state=="FL"
replace newname = "florida hospital" if hospname=="florida hospital orlando" & state=="FL"
replace newname = "healthsouth rehabilitation hospital" if hospname=="healthsouth rehab hospital of largo" & state=="FL"
replace newname = "holy cross hospital" if hospname=="holy cross hospital:fort lauderdale hosptial" & state=="FL"
replace newname = "largo medical center" if hospname=="largo medical of indian rocks" & state=="FL"
replace newname = "mayo clinic florida" if hospname=="mayo clinic jacksonville" & state=="FL"
replace newname = "mease hospital countryside" if (hospname=="mease countryside" | hospname=="mease countryside hospital") & state=="FL"
replace newname = "mease hospital and clinic" if hospname=="mease dunedin" & state=="FL"
replace newname = "morton plant north bay hospital" if hospname=="north bay hospital" & state=="FL"
replace newname = "regional medical centre bayonet poin" if hospname=="regional medical center bayonet point" & state=="FL"
replace newname = "st josephs hospital" if (hospname=="saint joseph hospital" | hospname=="st josephs hospital south" | hospname=="st josephs hospital tampa") & state=="FL"
replace newname = "st petersburg general" if hospname=="st petersburg general hospital" & state=="FL"

replace newname = "whittier hospital bradford" if hospname=="whittier rehab hospital" & state=="MA"
replace newname = "kfh hawaii" if hospname=="kaiser hospital moanalua medical center" & state=="HI"
replace newname = "queens medical center" if (hospname=="queens hospital" | hospname=="queens medical center west oahu") & state=="HI"

replace newname = "midwestern regional medical center" if hospname=="cancer treatment center midwestern region" & state=="IL"

replace newname = "bidmc milton hospital" if hospname=="beth israel deaconess hospital milton" & state=="MA"
replace newname = "jordan hospital" if (hospname=="beth israel deaconess hospital plymouth" | hospname=="beth israel deaconess hospital plymouth breast cen" | hospname=="beth israel deaconess hospital plymouth cancer cen") & state=="MA"
replace newname = "beth israel deaconess medical center" if hospname=="beth israel deaconess medical center farr 7" & state=="MA"
replace newname = "beth israel deaconess hospital needh" if hospname=="beth israel deaconess medical center needham" & state=="MA"
replace newname = "childrens hospital corporation" if (hospname=="boston childrens hospital" | hospname=="childrens hospital of boston") & state=="MA"
replace newname = "brockton hospital" if hospname=="brockton hospital tcu" & state=="MA"
replace newname = "steward carney hopsital" if hospname=="carney hospital" & state=="MA"
replace newname = "southcoast hospitals group inc" if hospname=="charlton memorial hospital" & state=="MA"
replace newname = "dana farber cancer institute" if hospname=="dana farber/brigham and womens cancer center" & state=="MA"
replace newname = "emerson hospital" if hospname=="emerson hospital center for wound care" & state=="MA"
replace newname = "metrowest medical center" if hospname=="framingham union hospital" & state=="MA"
replace newname = "good samaritan hospital" if (hospname=="good samaritan center for wound care" | hospname=="good samaritan hospital brockton") & state=="MA"
replace newname = "kindred hospital northeast" if hospname=="kindred hospital northeast stoughton" & state=="MA"
replace newname = "lahey clinic hospital" if (hospname=="lahey clinic medical center lexington" | hospname=="lahey hospital and medical center") & state=="MA"
replace newname = "metrowest medical center" if hospname=="leonard morse hospital" & state=="MA"
replace newname = "lowell general hospital" if hospname=="lowel general hospital" & state=="MA"
replace newname = "mass eye and ear infirmary" if hospname=="massachusetts eye and ear" & state=="MA"
replace newname = "metrowest medical center" if hospname=="metrowest" & state=="MA"
replace newname = "new bedford hospital" if hospname=="new bedford rehabilitation hospital" & state=="MA"
replace newname = "new england rehabilitation hospital" if hospname=="new england rehabilitation hospital at lowell" & state=="MA"
replace newname = "new england sinai hospital" if hospname=="new england sinai" & state=="MA"
replace newname = "steward norwood hospital" if hospname=="norwood caritas hospital" & state=="MA"
replace newname = "cape cod mental health center" if hospname=="pocasset mental health center" & state=="MA"
replace newname = "radius specialty hospital " if hospname=="radius specialty hospital" & state=="MA"
replace newname = "south shore hospital" if (hospname=="south shore hospital home care division" | hospname=="south shore medical center") & state=="MA"
replace newname = "spaulding rehabilitation hospital" if (hospname=="spalding rehabilitation hospital" | hospname=="spaulding rehabilitation hospital boston" | hospname=="spaulding outpatient rehabilitation" | hospname=="spaulding nursing and therapy center") & state=="MA"
replace newname = "rehab hospital of cape and islands" if hospname=="spaulding rehabilitation hospital cape cod" & state=="MA"
replace newname = "steward st annes hospital" if hospname=="st annes hospital" & state=="MA"
replace newname = "steward st elizabeths medical center" if hospname=="st elizabeths medical center" & state=="MA"
replace newname = "southcoast hospitals group inc" if hospname=="st lukes hospital new bedford" & state=="MA"
replace newname = "saint vincent hospital" if hospname=="st vincent hospital worcester ma" & state=="MA"
replace newname = "southcoast hospitals group inc" if hospname=="tobey hospital" & state=="MA"
replace newname = "ummhc~clinton hospital" if hospname=="umass clinton hospital" & state=="MA"
replace newname = "marlborough hospital" if hospname=="umass marlborough hospital" & state=="MA"
replace newname = "umass memorial medical center" if (hospname=="umass memorial campus" | hospname=="umass university campus") & state=="MA"
replace newname = "vibra hospital of western massachuse" if hospname=="vibra hospital rochdale ma" & state=="MA"
replace newname = "cambridge health alliance" if hospname=="whidden memorial hospital" & state=="MA"
replace newname = "" if hospname=="whittier rehab hospital" & state=="MA"
replace newname = "whittier hospital bradford" if hospname=="" & state=="MA"

replace newname = "anne arundel medical center inc" if (hospname=="anne arundel medical center annapolis" | hospname=="anne arundel medical center baltimore aamc") & state=="MD"
replace newname = "atlantic general hospital" if hospname=="atlantic central hospital" & state=="MD"
replace newname = "baltimore washington medical center" if hospname=="baltimore washington medical center bwmc" & state=="MD"
replace newname = "carroll county general hospital" if hospname=="carroll hospital center" & state=="MD"
replace newname = "suburban hospital" if hospname=="duplicate suburban bethesda hospital" & state=="MD"
replace newname = "franklin square hospital" if hospname=="franklin square hospital center" & state=="MD"
replace newname = "frederick memorial hospital" if (hospname=="frederick memorial hospital home care" | hospname=="frederick memorial hosptial") & state=="MD"
replace newname = "greater baltimore medical center" if (hospname=="gbmc wound care center" | hospname=="greater baltimore medical center gbmc") & state=="MD"
replace newname = "good samaritan hospital" if (hospname=="good samaritan hospital of maryland" | hospname=="good samaritan hospital of maryland duplicate") & state=="MD"
replace newname = "medstar harbor hospital" if hospname=="harbor hospital" & state=="MD"
replace newname = "holy cross hospital" if (hospname=="holy cross home care and hospice" | hospname=="holy cross hospital germantown") & state=="MD"
replace newname = "howard county" if hospname=="howard county general hospital" & state=="MD"
replace newname = "james lawrence kernan hospital" if (hospname=="james kernan rehab hospital" | hospname=="kernan hospital") & state=="MD"
replace newname = "johns hopkins hospital" if (hospname=="john hopkins community physicians internal medicin" | hospname=="john hopkins hospital" | hospname=="john hopkins home care connections" | hospname=="johns hopkins hospital main baltimore") & state=="MD"
replace newname = "johns hopkins bayview medical center" if (hospname=="johns hopkins community physicians east baltimore" | hospname=="johns hopkins home care greater baltimore medica") & state=="MD"
replace newname = "suburban hospital" if hospname=="kaiser" & state=="MD"
replace newname = "memorial easton" if hospname=="memorial hospital at easton" & state=="MD"
replace newname = "northwest hospital center" if hospname=="northwest hospital" & state=="MD"
replace newname = "st agnes hospital" if (hospname=="partner portal access st agnes hospital" | hospname=="saint agnes healthcare" | hospname=="st agnes hospital baltimore") & state=="MD"
replace newname = "howard county" if hospname=="pilot howard county general hospital" & state=="MD"
replace newname = "johns hopkins hospital" if hospname=="pilot john hopkins main" & state=="MD"
replace newname = "shady grove adventist hospital" if hospname=="shady grove hospital medical records" & state=="MD"
replace newname = "sheppard and enoch pratt hospital" if hospname=="sheppard pratt health system" & state=="MD"
replace newname = "sinai hospital of baltimore" if hospname=="sinai hospital baltimore" & state=="MD"
replace newname = "st joseph medical center" if (hospname=="st joes hospital towson duplicate" | hospname=="st joseph medical center duplicate" | hospname=="st joseph medical center towson duplicate" | hospname=="university of maryland at st joseph medical cente" | hospname=="university of maryland saint joseph center for adv") & state=="MD"
replace newname = "university of maryland med sys" if (hospname=="university of maryland medical center" | hospname=="university of maryland midtown campus" | hospname=="wound center at university of maryland midtown") & state=="MD"
replace newname = "upper chesapeake medical center" if (hospname=="upper chesapeake medical center comprehensive care" | hospname=="upper chesapeake medical center kaufman cancer cen") & state=="MD"
replace newname = "washington adventist hospital" if hospname=="washington adventist medical records" & state=="MD"

replace newname = "new england rehabilitation hospital" if hospname=="new england rehab hospital of portland" & state=="ME"
replace newname = "york hospital" if hospname=="york hospital maine" & state=="ME"

replace newname = "mayo clinic health sys new prague" if hospname=="mayo clinic" & state=="MN"

replace newname = "des peres medical center" if hospname=="des perez hospital" & state=="MO"

*starting from NC, only checked referral sources for which nadm >= 5
replace newname = "carolinas specialty hospital" if hospname=="carolinas continuecare pineville" & state=="NC"
replace newname = "carolinas rehabilitation" if hospname=="carolinas healthcare system levine cancer institutioncon" & state=="NC"
replace newname = "davie county emergency health corp" if hospname=="davie medical center" & state=="NC"
replace newname = "moses h cone memorial hospital" if (hospname=="day surgiery center moses cone" | hospname=="hri high risk initiative") & state=="NC"
replace newname = "duke regional hospital" if hospname=="duke outpatient clinic" & state=="NC"
replace newname = "kindred hospital greensboro" if hospname=="kindred hospital charlotte" & state=="NC"
replace newname = "carolinas medical center lincoln" if hospname=="lincoln medicad center" & state=="NC"
replace newname = "northern hosp of surry co" if (hospname=="northern hospital" | hospname=="mt airy hospital duplicate") & state=="NC"
replace newname = "forsyth memorial hospital" if hospname=="novant health wound care" & state=="NC"
replace newname = "presbyterian orthopaedic hospital" if hospname=="presbyterian orthopedic" & state=="NC"
replace newname = "ssh greensboro" if hospname=="select specialty hospital at moses cone greensboro" & state=="NC"
replace newname = "ssh durham" if (hospname=="select specialty hospital durham" | hospname=="select medical hospital") & state=="NC"
replace newname = "st lukes hospital" if hospname=="st lukes hospital columbus" & state=="NC"
replace newname = "stanly regional medical center" if hospname=="stanley regional medical center" & state=="NC"
replace newname = "thomasville medical center" if hospname=="thomasville medical center novant health" & state=="NC"
replace newname = "north carolina baptist hospital" if hospname=="wake forest university school of medicine dept of" & state=="NC"
replace newname = "wakemed raleigh campus" if (hospname=="wake med rehab hospital" | hospname=="wake med north") & state=="NC"
replace newname = "forsyth memorial hospital" if hospname=="whitaker rehabilitation" & state=="NC"
replace newname = "cleveland regional medical center" if hospname=="wound healing center cleveland regional medical" & state=="NC"

replace newname = "chi health good samaritan" if hospname=="good samaritan hospital of nebraska" & state=="NE"


replace newname = "moses h cone memorial hospital" if hospname=="annie penn hospital" & state=="NC"
replace newname = "kings mountain hospital" if hospname=="carolinas continuecare hospital at kings mountain" & state=="NC"
replace newname = "valdese general hospital" if hospname=="carolinas healthcare system" & state=="NC"
replace newname = "carolinas rehabilitation" if hospname=="carolinas rehabilitation center" & state=="NC"
replace newname = "gaston memorial hospital" if hospname=="caromont regional medical center" & state=="NC"
replace newname = "carolinas rehabilitation" if hospname=="cmc and levine children hospital" & state=="NC"
replace newname = "carolinas medical center lincoln" if hospname=="cmc lincoln" & state=="NC"
replace newname = "carolinas medical center" if hospname=="cmc main" & state=="NC"
replace newname = "mercy hospitals" if (hospname=="cmc mercy" | hospname=="cmc pineville") & state=="NC"
replace newname = "union regional medical center" if hospname=="cmc union" & state=="NC"
replace newname = "carolinas medical center university" if hospname=="cmc university" & state=="NC"
replace newname = "duke university hospital" if (hospname=="duke university medical center durham" | hospname=="duplicate duke university hospital" | hospname=="duplicate duke university medical center") & state=="NC"
replace newname = "duke regional hospital" if hospname=="durham rehabilitation institute" & state=="NC"
replace newname = "firsthealth moore regional hospital" if hospname=="first health moore regional hospital" & state=="NC"
replace newname = "forsyth memorial hospital" if hospname=="forsyth medical center" & state=="NC"
replace newname = "high point regional health" if hospname=="high point regional health system" & state=="NC"
replace newname = "holly hills hospital" if hospname=="holly hill hospital" & state=="NC"
replace newname = "forsyth memorial hospital" if hospname=="kernersville hospital" & state=="NC"
replace newname = "lake norman regional medical center" if hospname=="lake norman regional hospital" & state=="NC"
replace newname = "lexington memorial hospital" if hospname=="lexington medical center" & state=="NC"
replace newname = "moses h cone memorial hospital" if hospname=="moses cone health system" & state=="NC"
replace newname = "presbyterian hospital" if (hospname=="novant health" | hospname=="novant health pmc" | hospname=="presbyterian hospital charlotte") & state=="NC"
replace newname = "person memorial hospita inc" if hospname=="person memorial hospital" & state=="NC"
replace newname = "rex hospital" if hospname=="rex healthcare hospital" & state=="NC"
replace newname = "rowan regional hospital" if hospname=="rowan regional medical center" & state=="NC"
replace newname = "ssh winston salem" if hospname=="select specialty hospital winston salem" & state=="NC"
replace newname = "university of north carolina hospital" if (hospname=="unc hospital" | hospname=="unc university of north carolina hospitals") & state=="NC"
replace newname = "north carolina baptist hospital" if hospname=="wake forest university baptist hospital" & state=="NC"
replace newname = "wakemed raleigh campus" if hospname=="wake med health and hospital" & state=="NC"
replace newname = "moses h cone memorial hospital" if hospname=="wesley long community hospital" & state=="NC"
replace newname = "lexington memorial hospital" if hospname=="wound care center of lexington" & state=="NC"

replace newname = "alice peck day memorial hospital" if hospname=="alice peck day hospital" & state=="NH"
replace newname = "mary hitchcock memorial hosp" if hospname=="dartmouth hitchcock medical center dhmc" & state=="NH"
replace newname = "healthsouth rehabilitation hospital" if hospname=="healthsouth rehabilitation hospital of concord" & state=="NH"


replace newname = "capital health med center hopewell" if hospname=="capitol health medical center hopewell" & state=="NJ"
replace newname = "rehab hospital at raritan bay" if hospname=="care one at raritan bay medical center" & state=="NJ"
replace newname = "cooper university hospital" if (hospname=="cooper cancer institute camden" | hospname=="cooper neurological institute") & state=="NJ"

replace newname = "deborah heart and lung center" if hospname=="deborah wound care center" & state=="NJ"
replace newname = "mountainside hospital" if hospname=="hackensack umc mountainside" & state=="NJ"
replace newname = "hackettstown regional medical cente" if hospname=="hackettstown regional medical center" & state=="NJ"
replace newname = "healthsouth rehab of south jersey (v" if (hospname=="healthsouth rehabilitation hospital of vineland du" | hospname=="duplicate health south rehabilitation hospital o") & state=="NJ"
replace newname = "inspira medical center vineland" if hospname=="inspira bridgeton dialysis unit" & state=="NJ"
replace newname = "inspira medical center vineland" if hospname=="inspira ? south jersey regional medical center rmc" & state=="NJ"
replace newname = "kindred hospital new jersey" if hospname=="kindred hospital nj rahway" & state=="NJ"
replace newname = "cooper university hospital" if hospname=="md anderson cooper" & state=="NJ"
replace newname = "newton medical center" if hospname=="newton health center" & state=="NJ"
replace newname = "northbrook behavioral health hospita" if hospname=="northbrook behavioral health hospital" & state=="NJ"
replace newname = "mh ocean medical center" if hospname=="ocean medical center" & state=="NJ"
replace newname = "ramapo ridge psychiatric" if hospname=="ramapo ridge psychiatric hospital" & state=="NJ"
/* replace newname = "" if hospname=="rothman institute egg harbor" & state=="NJ" */
replace newname = "runnells specialized hospital" if hospname=="runnells center for rehab and healthcare" & state=="NJ"
replace newname = "saint barnabas medical center" if hospname=="saint barnabas health care system" & state=="NJ"
replace newname = "st clares hospital denville" if (hospname=="saint claires hospital" | hospname=="saint clares hospital") & state=="NJ"
replace newname = "st marys hospital passaic" if hospname=="saint marys passaic" & state=="NJ"
replace newname = "st peters university hospital" if (hospname=="saint peters" | hospname=="saint peters university hospital") & state=="NJ"
replace newname = "st francis medical center" if hospname=="st francis medical center nj" & state=="NJ"
replace newname = "st josephs hospital and medical center" if hospname=="st josephs regional medical center patterson" & state=="NJ"
replace newname = "trinitas hospital" if hospname=="trinitas regional medical center" & state=="NJ"
replace newname = "university medical center at princet" if hospname=="university medical center of princeton" & state=="NJ"
replace newname = "west jersey health system" if hospname=="west jersey hospital marlton" & state=="NJ"
replace newname = "hoboken university medical center" if hospname=="wound care at hoboken university medical center" & state=="NJ"
replace newname = "palisades medical center" if hospname=="wound care at palisades medical center" & state=="NJ"

replace newname = "acuity specialty hosp of new jersey" if hospname=="acuity specialty hospital" & state=="NJ"
replace newname = "atlanticare regional medical center" if (hospname=="atlanticare regional medical center ac" | hospname=="atlanticare regional medical center ga" | hospname=="atlanticare regional medical center galloway") & state=="NJ"
replace newname = "capital health med center hopewell" if hospname=="capital health medical center hopewell" & state=="NJ"
replace newname = "helene fuld medical center" if hospname=="capital health regional medical center trenton" & state=="NJ"
replace newname = "centra state medical center" if hospname=="centrastate medical center" & state=="NJ"
replace newname = "chilton hospital" if hospname=="chilton memorial hospital" & state=="NJ"

replace newname = "columbus hospital ltach" if hospname=="columbus hospital" & state=="NJ"
replace newname = "community medical center" if hospname=="community medical center/saint barnabas health sys" & state=="NJ"
replace newname = "cooper university hospital" if (hospname=="cooper bone and joint institute" | hospname=="cooper cancer institute voorhees") & state=="NJ"
replace newname = "hackensack university medical center" if hospname=="hackensack medical center" & state=="NJ"
replace newname = "healthsouth of toms river " if hospname=="healthsouth" & state=="NJ"
replace newname = "hoboken university medical center" if hospname=="hoboken university hospital" & state=="NJ"
replace newname = "" if hospname=="inspira medical center underwood memorial" & state=="NJ"
replace newname = "inspira medical center woodbury" if hospname=="inspira medical center underwood memorial" & state=="NJ"
replace newname = "south jersey hospital rmc" if hospname=="inspira – south jersey regional medical center rmc" & state=="NJ"
replace newname = "jfk medical center" if hospname=="jfk health system" & state=="NJ"
replace newname = "kennedy university hospital" if (hospname=="kennedy health system corporate" | hospname=="kennedy memorial hospital cherry hill" | hospname=="kennedy memorial hospitals" | hospname=="kennedy university hospital washington twp" | hospname=="kennedy university hosptial stratford") & state=="NJ"
replace newname = "lourdes specialty hospital" if hospname=="lourdes specialty hospital of south jersey" & state=="NJ"
replace newname = "lourdes medical center burlington" if hospname=="lourdes wound healing" & state=="NJ"
replace newname = "meadowlands hospital medical center" if hospname=="meadowlands hospital" & state=="NJ"
replace newname = "princeton healthcare system" if hospname=="medical center of princeton" & state=="NJ"
replace newname = "our lady of lourdes medical center" if (hospname=="our lady of lourdes hospital duplicate" | hospname=="our lady of lourdes medical center of camden") & state=="NJ"
replace newname = "rancocas hospital" if hospname=="our lady of lourdes medical center of burlington c" & state=="NJ"
replace newname = "rwj university hospital hamilton" if hospname=="robert wood johnson university hosp at hamilton" & state=="NJ"
replace newname = "robert wood johnson university hosp" if hospname=="robert wood university" & state=="NJ"
replace newname = "st michaels medical center" if hospname=="saint michaels medical center" & state=="NJ"
replace newname = "ssh northeast new jersey" if hospname=="select specialty hospital rochelle" & state=="NJ"
replace newname = "shore memorial hospital" if hospname=="shore medical center" & state=="NJ"
replace newname = "st josephs hospital and medical center" if hospname=="st josephs wayne hospital" & state=="NJ"
replace newname = "uh university hospital" if hospname=="university hospital" & state=="NJ"
replace newname = "west jersey health system" if (hospname=="virtua hospital voorhees" | hospname=="virtua marlton hospital") & state=="NJ"
replace newname = "memorial hosp of burlington cty" if hospname=="virtua mt holly hospital" & state=="NJ"

replace newname = "lovelace westside hospital" if hospname=="lovelace westside" & state=="NM"
replace newname = "presbyterian hospital" if hospname=="presbyterian statewide" & state=="NM"
replace newname = "university of new mexico hospital" if hospname=="unm hospital" & state=="NM"
replace newname = "artesia general hospital" if hospname=="artesia hospital" & state=="NM"
replace newname = "heart hospital of new mexico" if hospname=="heart hospital" & state=="NM"
replace newname = "st vincent hospital" if hospname=="st vincent regional medical center alv" & state=="NM"
replace newname = "university of new mexico hospital" if hospname=="unm sr health clinic" & state=="NM"

replace newname = "albany medical center hospital" if hospname=="albany medical center" & state=="NY"
replace newname = "bon secours community hospital" if hospname=="bon secours hospital ny" & state=="NY"
replace newname = "memorial hospital for cancer and all" if (hospname=="memorial hospital for cancer and allied diseases" | hospname=="memorial sloan kettering" | hospname=="memorial sloan kettering cancer center") & state=="NY"
replace newname = "mount sinai hospital" if (hospname=="mount sinai hospital new york" | hospname=="mount sinai hospital new york duplicate") & state=="NY"
replace newname = "new york presbyterian hospital" if hospname=="new york weill cornell medical center" & state=="NY"
replace newname = "north shore university hospital" if hospname=="north shore university" & state=="NY"
replace newname = "nyu hospitals center" if (hospname=="nyu hospital for joint diseases" | hospname=="nyu langone medical center" | hospname=="nyu medical center") & state=="NY"
replace newname = "summit park hospital/care center" if hospname=="summit park" & state=="NY"

replace newname = "cleveland clinic hospital" if hospname=="cleveland clinic" & state=="OH"
replace newname = "childrens hospital medical center" if hospname=="incinnati childrens hospital medical center" & state=="OH"

replace newname = "hillcrest medical center" if hospname=="hillcrest medical center tulsa" & state=="OK"
replace newname = "saint francis hospital" if hospname=="saint francis hospital tulsa" & state=="OK"
replace newname = "st john medical center" if hospname=="saint john medical center" & state=="OK"

replace newname = "mary imogene bassett hospita" if hospname=="bassett healthcare network" & state=="NY"

replace newname = "new york presbyterian hospital" if (hospname=="columbia orthopaedics" | hospname=="milstein hospital") & state=="NY"
replace newname = "glens falls hopsital" if hospname=="glen falls hospital" & state=="NY"
replace newname = "hospital for special surgery" if hospname=="hospital for special surgery service" & state=="NY"
replace newname = "our lady of lourdes memorial hosp" if hospname=="lourdes hospital ny" & state=="NY"
replace newname = "mercy medical center" if hospname=="mercy medical center new york" & state=="NY"
replace newname = "mount sinai hospital" if hospname=="mount sinai hematology" & state=="NY"
replace newname = "new york hospital of queens" if hospname=="new york hospital queens" & state=="NY"
replace newname = "new york presbyterian hospital" if hospname=="new york prebyterian childrens hospital" & state=="NY"
replace newname = "northern westchester hospital" if hospname=="northern westchester hospital center" & state=="NY"
replace newname = "st lukes roosevelt hospital center" if hospname=="st lukes roosevelt hospital" & state=="NY"
replace newname = "st peters hospital" if hospname=="st peters hospital 1" & state=="NY"
replace newname = "uhs" if hospname=="united health services hospitals" & state=="NY"


replace newname = "lansdale hospital" if (hospname=="abington lansdale health center" | hospname=="abington lansdale hospital rehab") & state=="PA"
replace newname = "hospital of the univ of penna" if (hospname=="abramson cancer center" | hospname=="abramson cancer center at penn presbyterian medica") & state=="PA"
replace newname = "aria health" if (hospname=="aria health: bucks campus" | hospname=="aria health: frankford campus" | hospname=="aria health: torresdale campus") & state=="PA"
replace newname = "pottstown memorial medical center" if (hospname=="pottstown memorial medical center wound center" | hospname=="center for wound healing, pmmc duplicate do not") & state=="PA"
replace newname = "pocono medical center" if hospname=="advanced wound care center at pmc bartonsville" & state=="PA"
replace newname = "altoona regional health system" if hospname=="altoona regional health systems" & state=="PA"
replace newname = "belmont center for comp treatment" if hospname=="belmont behavioral health" & state=="PA"
replace newname = "paoli hospital" if hospname=="cancer center of paoli hospital" & state=="PA"
replace newname = "eastern regional medical center" if (hospname=="cancer treatment center of america eastern region" | hospname=="cancer treatment centers of america eastern region") & state=="PA"
replace newname = "chester county hospital" if hospname=="chester county hospital and health system" & state=="PA"
replace newname = "childrens hospital of philadelph" if hospname=="childrens hospital of philadelphia chop" & state=="PA"
replace newname = "community medical center" if hospname=="community medical center scranton" & state=="PA"
replace newname = "memorial medical center" if hospname=="conemaugh memorial medical center" & state=="PA"
replace newname = "coordinated hospital of allentown" if hospname=="coordinated health allentown" & state=="PA"
replace newname = "coordinated health orthopedic hosp" if hospname=="coordinated health bethlehem" & state=="PA"
replace newname = "crozer chester medical center" if (hospname=="crozer keystone" | hospname=="crozer keystone health system" | hospname=="crozer medical health") & state=="PA"
replace newname = "doylestown hospital" if (hospname=="do not use:doylestown hospitalist associates" | hospname=="doylestown hospital er") & state=="PA"
*drexel univeristy college of medicine : doesn't have its own hospital, so skip
replace newname = "st luke hospital anderson campus" if (hospname=="duplciate st lukes anderson campus" | hospname=="st lukes hospital anderson") & state=="PA"
replace newname = "st lukes hospital" if (hospname=="duplicate st luke hospital bethlehem" | hospname=="duplicate st lukes bethlehem campus" | hospname=="duplicate st lukes hospital allentown") & state=="PA"
replace newname = "quakertown community hospital" if (hospname=="duplicate st lukes health network quakertown" | hospname=="st lukes hospital quakertown") & state=="PA"
replace newname = "alfred i dupont hosp for children" if hospname=="dupont hospital" & state=="PA"
replace state = "DE" if newname=="alfred i dupont hosp for children" & state=="PA"
replace newname = "american oncologic hospital" if hospname=="fox chase cancer center" & state=="PA"
replace newname = "community medical center" if hospname=="geisinger cmc wound care center" & state=="PA"
replace newname = "geisinger medical center" if (hospname=="geisinger danville" ) & state=="PA"
replace newname = "geisinger wyoming valley medical center" if (hospname=="geisinger podiatry" | hospname=="geisinger pittston" | hospname=="geisinger wyoming valley" | hospname=="geisinger wyoming valley cancer center") & state=="PA"
replace newname = "gnaden huetten memorial hospital" if hospname=="gnaden huetten memorial hospital lehighton" & state=="PA"
replace newname = "good samaritan hospital" if hospname=="good samaritan health system" & state=="PA"
replace newname = "hahnemann university hospital" if hospname=="hahnemann heart failure clinic" & state=="PA"
replace newname = "haven behavioral hospital philadelphia" if hospname=="haven behavioral health" & state=="PA"
replace newname = "healthsouth nittany valley rehabilit" if hospname=="healthsouth nittany valley rehab hospital" & state=="PA"
replace newname = "lifecare hospital of mechanicsburg" if hospname=="healthsouth regional specialty hospital" & state=="PA"
replace newname = "doylestown hospital" if hospname=="heart institute of doylestown hospital" & state=="PA"
replace newname = "heart of lancaster regional medical" if hospname=="heart of lancaster regional medical center" & state=="PA"
replace newname = "milton s hershey medical center" if (hospname=="hershey medical center" | hospname=="penn state hershey cancer institute" | hospname=="penn state milton s hmc plastic surgery clinic hu0") & state=="PA"
replace newname = "hospital" if hospname=="holy redeemer hospital" & state=="PA"
*holy redeemer hospital has prvdr = 390097
replace newname = "hospital of the univ of penna" if hospname=="hospital of the university of pennsylvania" & state=="PA"
replace newname = "thomas jefferson univ hospital" if (hospname=="jefferson internal medicine" | hospname=="jefferson medical oncology kimmel cancer center" | hospname=="jefferson neurology" | hospname=="jefferson neurosurgical associates" | hospname=="jefferson hospital duplicate" | hospname=="jefferson rehabilitation association") & state=="PA"
*kindred hospital of easton closed
replace newname = "lancaster regional medical center" if hospname=="lancaster reg med cenorthern behavioral health unit" & state=="PA"
replace newname = "lehigh valley" if (hospname=="lehigh valley hospital 17th and chew" | hospname=="lehigh valley hospital cedar crest" | hospname=="lehigh valley hospital outpatient burn center") & state=="PA"
replace newname = "muhlenberg hospital center" if hospname=="lehigh valley hospital muhlenberg center" & state=="PA"
replace newname = "lifecare hospital of pittsburgh" if hospname=="lifecare hospital" & state=="PA"
replace newname = "mercy catholic medical center" if (hospname=="mercy fitzgerald hospital" | hospname=="mercy philadelphia hospital") & state=="PA"
replace newname = "thomas jefferson univ hospital" if hospname=="methodist hospital" & state=="PA"
replace newname = "nazareth hospital phila pa" if hospname=="nazareth hospital" & state=="PA"
replace newname = "st lukes hospital" if hospname=="neurology associates of monroe county" & state=="PA"
replace newname = "oss orthopaedic hospital" if hospname=="orthopaedic and spine specialists hospital" & state=="PA"
replace newname = "good shepherd penn partners" if hospname=="penn medicine at rittenhouse" & state=="PA"
replace newname = "presbyterian medical center" if hospname=="penn presbyterian medical center phila" & state=="PA"
replace newname = "penn state hershey rehabilitation ll" if hospname=="penn state hershey rehabilitation wound care cente" & state=="PA"
replace newname = "pennsylvania hospital of uphs" if hospname=="pennsylvania hospital" & state=="PA"
replace newname = "hospital of the univ of penna" if hospname=="pennsylvania oncology hematology asso" & state=="PA"
replace newname = "phoenixville hospital" if hospname=="phoenixville hospital cancer center" & state=="PA"
replace newname = "physicians care surgical hospital" if hospname=="physician care surgery hospital" & state=="PA"
replace newname = "pinnacle health hospitals" if (hospname=="pinnacle health cancer center" | hospname=="pinnacle health harrisburg campus" | hospname=="pinnacle health family care of middletown" | hospname=="pinnacle health west shore" | hospname=="pinnaclehealth community general osteopathic hos") & state=="PA"
replace newname = "reading hospital and medical center" if hospname=="reading hospital" & state=="PA"
replace newname = "regional hospital of scranton" if (hospname=="regional hospital" | hospname=="regional hospital of scranton wound care center") & state=="PA"
replace newname = "bucks county specialty hospital" if hospname=="rothman institute" & state=="PA"
replace newname = "roxborough memorial hospital" if hospname=="roxborough memorial wound healing center" & state=="PA"
replace newname = "st joseph medical center" if hospname=="saint joseph medical center reading" & state=="PA"
replace newname = "st joseph hospital" if hospname=="saint josephs hospital philadelphia" & state=="PA"
replace newname = "saint vincent health center" if hospname=="saint vincent health system" & state=="PA"
replace newname = "schuylkill medical center south" if hospname=="schuylkill medical center" & state=="PA"
replace newname = "schuylkill medical center east" if hospname=="schuylkill medical center east norwegian" & state=="PA"
replace newname = "ssh central pa" if (hospname=="select specialty hospital camp hill" | hospname=="select specialty hospital harrisburg") & state=="PA"
replace newname = "shc philadelphia" if hospname=="shriners hospital for children" & state=="PA"
replace newname = "mercy special care" if (hospname=="special care hospital" | hospname=="special care hospital scranton") & state=="PA"
replace newname = "crozer chester medical center" if hospname=="springfield hospital pa" & state=="PA"
replace newname = "st christophers hospital for childr" if hospname=="st christophers hospital" & state=="PA"
replace newname = "st clair memorial hospital" if hospname=="st clair hospital" & state=="PA"
replace newname = "st lukes hospital" if (hospname=="st lukes hospital allentown" | hospname=="st lukes hospital and acute rehab bethlehem" | hospname=="st lukes hospital and health network") & state=="PA"
replace newname = "miners memorial medical center" if hospname=="st lukes miners memorial hospital and rehab" & state=="PA"
replace newname = "mercy suburban hospital" if hospname=="suburban community hospital formally mercy sub" & state=="PA"
replace newname = "crozer chester medical center" if hospname=="taylor hospital" & state=="PA"
replace newname = "temple university hospital" if (hospname=="temple heart center" | hospname=="temple internal medecine") & state=="PA"
replace newname = "thomas jefferson univ hospital" if hospname=="thomas jefferson university hospital" & state=="PA"
replace newname = "upmc mercy hospital" if hospname=="university of pittsburgh medical center" & state=="PA"
replace newname = "upmc east" if hospname=="university of pittsburgh medical center east" & state=="PA"
replace newname = "wellspan surgery and rehab hospital" if hospname=="wellspan surgery and rehabilitation hospital" & state=="PA"
replace newname = "york hospital" if hospname=="wellspan york hospital" & state=="PA"
replace newname = "western pennsylvania hospital" if hospname=="western pennsylvania hosptial" & state=="PA"
replace newname = "westfield medical center" if hospname=="westfield hospital" & state=="PA"
replace newname = "williamsport hospital and medical center" if hospname=="williamsport regional medical center" & state=="PA"
replace newname = "wayne memorial hospital" if hospname=="wound care and hyperbaric center at wayne memorial" & state=="PA"
replace newname = "wilkes barre general hospital" if hospname=="wound healing center wilkes barre general hospital" & state=="PA"
replace newname = "bucks county specialty hospital" if hospname=="rothman specialty hospital" & state=="PA"

replace newname = "bryn mawr hospital" if hospname=="wound healing center in bryn mawr" & state=="PA"
replace newname = "abington memorial hospital" if hospname=="rosenfeld cancer center" & state=="PA"
replace newname = "reading hospital and medical center" if hospname=="reading hospital cancer infusion center" & state=="PA"
replace type = "HOME HEALTH AGENCY" if hospname=="neighborhood health" & state=="PA"
replace newname = "pottstown memorial medical center" if hospname=="center for wound healing, pmmc duplicate do not" & state=="PA"
replace newname = "hahnemann university hospital" if hospname=="drexel univeristy college of medicine" & state=="PA"
replace newname = "easton hospital" if hospname=="kindred hospital of easton" & state=="PA"

replace newname = "rehabilitation hospital of ri" if hospname=="rehabilitation hospital of rhode island" & state=="RI"

replace newname = "grand strand regional medical center" if hospname=="grand starnd regional medical center" & state=="SC"

replace newname = "johnson county community hospital" if hospname=="mountain states health alliance" & state=="TN"



*Recheck RI -WY states
*VA
replace newname = "university of virginia medical cente" if (hospname=="university of virginia medical center") & state=="VA"
replace newname = "vcu health system mcv hospital" if hospname=="vcu medical center" & state=="VA"

*VT
replace newname = "university of vermont medical center" if (hospname=="fanny allen hospital" | hospname=="university of vermont medical center fahc uvmmc") & state=="VT"
replace newname = "central vermont hospital" if hospname=="central vermont medical center" & state=="VT"

replace newname = "northeastern vt regional hospital" if hospname=="northeastern vermont regionalhospital" & state=="VT"

replace newname = "southwestern vermont medical center" if hospname=="southwestern vermont medical center svmc" & state=="VT"
replace newname = "rutland regional medical center" if hospname=="rutland regional medical center rrmc" & state=="VT"
replace newname = "porter hospital" if hospname=="porter medical center" & state=="VT"
replace newname = "mt ascutney hospital and health cent" if hospname=="mt ascutney hospital and health center" & state=="VT"

replace state = "NH" if hospname=="cheshire medical center/dartmouth hitchcock keene" & state=="VT"
replace newname = "cheshire medical center" if hospname=="cheshire medical center/dartmouth hitchcock keene" & state=="NH"

compress
save post_hncorrect, replace
